# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://tlog.296093.xyz
date_format: "ordinal"
title: 清风
subtitle: "笔记"
keywords: 测试, 测试开发
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 清风
github_username: zbeady
location: ChongQing, China
email: zbeady@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:title/
plugins:
    - jekyll-github-metadata
    - rouge
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zbeady/zbeady.github.io
